/**
 * controllers/postController.js — request handlers for the /posts resource.
 *
 * MIGRATED TO MONGODB: the in-memory array from data/posts.js is gone. Every
 * handler is now `async` and awaits Mongoose queries (routes wrap them in
 * asyncHandler, so a database error becomes a JSON response).
 *
 * The response shape is deliberately unchanged, so the existing frontend /
 * Postman collection keeps working.
 */

const Post = require('../models/Post');
const Comment = require('../models/Comment');

// Fixed page size required by the task spec
const POSTS_PER_PAGE = 10;

/**
 * Converts the ?page= query parameter to a safe positive integer.
 * Anything invalid ("abc", "0", "-3", missing) falls back to page 1.
 *
 * @param {unknown} value
 * @returns {number}
 */
function parsePage(value) {
  const page = Number.parseInt(value, 10);
  return Number.isInteger(page) && page > 0 ? page : 1;
}

/**
 * The blog API uses numeric ids, so "abc" can never be a post id.
 *
 * @param {unknown} value
 * @returns {number|null} the numeric id, or null when it is not a number
 */
function parseNumericId(value) {
  const parsed = Number(value);
  return Number.isInteger(parsed) ? parsed : null;
}

/**
 * GET /posts  (and GET /posts?page=1)
 *
 * Returns 10 posts per page plus pagination metadata.
 */
async function getPosts(req, res) {
  const requestedPage = parsePage(req.query.page);
  const skip = (requestedPage - 1) * POSTS_PER_PAGE;

  // Count and page in parallel — both only need the database
  const [totalPosts, posts] = await Promise.all([
    Post.countDocuments(),
    Post.find().sort({ id: 1 }).skip(skip).limit(POSTS_PER_PAGE),
  ]);

  const totalPages = Math.ceil(totalPosts / POSTS_PER_PAGE);

  return res.status(200).json({
    success: true,
    currentPage: requestedPage,
    totalPosts,
    totalPages,
    postsPerPage: POSTS_PER_PAGE,
    count: posts.length,
    hasNextPage: requestedPage < totalPages,
    hasPrevPage: requestedPage > 1,
    posts,
  });
}

/**
 * GET /posts/:id
 * 404 when the post does not exist (or the id is not a number).
 */
async function getPostById(req, res) {
  const postId = parseNumericId(req.params.id);
  const post = postId === null ? null : await Post.findOne({ id: postId });

  if (!post) {
    return res.status(404).json({
      success: false,
      message: `Post with id ${req.params.id} not found.`,
    });
  }

  return res.status(200).json({ success: true, post });
}

/**
 * POST /posts
 * Body is already validated (title + body) by middleware/validation.js.
 * Returns 201 Created with the new post.
 */
async function createPost(req, res) {
  // Numeric ids are generated by the model (see Post.nextId)
  const id = await Post.nextId();

  const post = await Post.create({
    id,
    title: req.body.title,
    body: req.body.body,
    author: req.body.author, // undefined → schema default "Anonymous"
  });

  return res.status(201).json({
    success: true,
    message: 'Post created successfully.',
    post,
  });
}

/**
 * PUT /posts/:id
 * Body is already validated by middleware/validation.js.
 * 404 when the post does not exist.
 */
async function updatePost(req, res) {
  const postId = parseNumericId(req.params.id);
  const post = postId === null ? null : await Post.findOne({ id: postId });

  if (!post) {
    return res.status(404).json({
      success: false,
      message: `Post with id ${req.params.id} not found.`,
    });
  }

  post.title = req.body.title;
  post.body = req.body.body;
  if (req.body.author) post.author = req.body.author;
  await post.save(); // runs the schema validation again

  return res.status(200).json({
    success: true,
    message: 'Post updated successfully.',
    post,
  });
}

/**
 * DELETE /posts/:id
 * Also removes the comments that belong to the post (no orphans).
 * 404 when the post does not exist.
 */
async function deletePost(req, res) {
  const postId = parseNumericId(req.params.id);

  // Check existence FIRST so a 404 never modifies any data
  const post = postId === null ? null : await Post.findOne({ id: postId });

  if (!post) {
    return res.status(404).json({
      success: false,
      message: `Post with id ${req.params.id} not found.`,
    });
  }

  const deletedComments = await Comment.deleteMany({ postId: post.id });
  await post.deleteOne();

  return res.status(200).json({
    success: true,
    message: 'Post deleted successfully.',
    deletedPost: post,
    deletedComments: deletedComments.deletedCount,
  });
}

module.exports = {
  getPosts,
  getPostById,
  createPost,
  updatePost,
  deletePost,
  POSTS_PER_PAGE,
};
